[[Xorg_xcb_util_renderutil]]
arch = "aarch64"
git-tree-sha1 = "bd9ce3739599e8538d28d3fc568b028f95502120"
libc = "glibc"
os = "linux"

    [[Xorg_xcb_util_renderutil.download]]
    sha256 = "201b155d509b8e20cdbb3cbe9ebc56044888bc6e4a733239004154777305a6e3"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_renderutil_jll.jl/releases/download/Xorg_xcb_util_renderutil-v0.3.10+0/Xorg_xcb_util_renderutil.v0.3.10.aarch64-linux-gnu.tar.gz"
[[Xorg_xcb_util_renderutil]]
arch = "aarch64"
git-tree-sha1 = "c7164a23b02e5b2bbb4843158204772fb8507901"
libc = "musl"
os = "linux"

    [[Xorg_xcb_util_renderutil.download]]
    sha256 = "d2b67eec8e9c57c3510a8559b5a1e591fbfc98eb3ce816a35390d4c5a56de854"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_renderutil_jll.jl/releases/download/Xorg_xcb_util_renderutil-v0.3.10+0/Xorg_xcb_util_renderutil.v0.3.10.aarch64-linux-musl.tar.gz"
[[Xorg_xcb_util_renderutil]]
arch = "aarch64"
git-tree-sha1 = "6fd204a61cb7c6d5ccc6258984f237ea0e8a7ff7"
os = "freebsd"

    [[Xorg_xcb_util_renderutil.download]]
    sha256 = "6f3473e6ee2b99c7a7c11a1cfe6dd636c32bd4e4bb052460b69e048854dd8c86"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_renderutil_jll.jl/releases/download/Xorg_xcb_util_renderutil-v0.3.10+0/Xorg_xcb_util_renderutil.v0.3.10.aarch64-unknown-freebsd.tar.gz"
[[Xorg_xcb_util_renderutil]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4d8edf62e1656cbb7fc8027e2240ad8323e9435a"
libc = "glibc"
os = "linux"

    [[Xorg_xcb_util_renderutil.download]]
    sha256 = "95888493121c86cae0e5db21f13fbbae0e8fd2c993a8617e26027231b719d1f3"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_renderutil_jll.jl/releases/download/Xorg_xcb_util_renderutil-v0.3.10+0/Xorg_xcb_util_renderutil.v0.3.10.armv6l-linux-gnueabihf.tar.gz"
[[Xorg_xcb_util_renderutil]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a29a64736ef304b40635eb7f0cbc3db48cce7bcd"
libc = "musl"
os = "linux"

    [[Xorg_xcb_util_renderutil.download]]
    sha256 = "a5e598d5de13d36255e71a6dfab17305beef7aa2d51eb67eb9d6fb61c8f6944d"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_renderutil_jll.jl/releases/download/Xorg_xcb_util_renderutil-v0.3.10+0/Xorg_xcb_util_renderutil.v0.3.10.armv6l-linux-musleabihf.tar.gz"
[[Xorg_xcb_util_renderutil]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8767129263d004959203fd3954084a036ef8807f"
libc = "glibc"
os = "linux"

    [[Xorg_xcb_util_renderutil.download]]
    sha256 = "be4e616fb0e893779e6288a8657a5e7910f59dcaec4b5855fb43f7e679d68e82"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_renderutil_jll.jl/releases/download/Xorg_xcb_util_renderutil-v0.3.10+0/Xorg_xcb_util_renderutil.v0.3.10.armv7l-linux-gnueabihf.tar.gz"
[[Xorg_xcb_util_renderutil]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4b4eda3833b2ec94afd992fed1729bce1e445ca3"
libc = "musl"
os = "linux"

    [[Xorg_xcb_util_renderutil.download]]
    sha256 = "c47a40e2a8bf41661f408d66927ccf8560ee946418dcc89a1cefde388f7d7db7"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_renderutil_jll.jl/releases/download/Xorg_xcb_util_renderutil-v0.3.10+0/Xorg_xcb_util_renderutil.v0.3.10.armv7l-linux-musleabihf.tar.gz"
[[Xorg_xcb_util_renderutil]]
arch = "i686"
git-tree-sha1 = "5323b7af84cc4d53acf48272d723855c0102c410"
libc = "glibc"
os = "linux"

    [[Xorg_xcb_util_renderutil.download]]
    sha256 = "cbbe8ca5eaa8e249c42b8de313c206dad66eace7c69d47ebf297e899fd6bbe43"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_renderutil_jll.jl/releases/download/Xorg_xcb_util_renderutil-v0.3.10+0/Xorg_xcb_util_renderutil.v0.3.10.i686-linux-gnu.tar.gz"
[[Xorg_xcb_util_renderutil]]
arch = "i686"
git-tree-sha1 = "ce30399f41d745dc2df11475ee3208b74cecb51c"
libc = "musl"
os = "linux"

    [[Xorg_xcb_util_renderutil.download]]
    sha256 = "e49abcf202f5016319a04c2cc2f5a8094706407352bba463667a555fa342981e"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_renderutil_jll.jl/releases/download/Xorg_xcb_util_renderutil-v0.3.10+0/Xorg_xcb_util_renderutil.v0.3.10.i686-linux-musl.tar.gz"
[[Xorg_xcb_util_renderutil]]
arch = "powerpc64le"
git-tree-sha1 = "62a40101fe4553063b7d68bac3914286dd15c888"
libc = "glibc"
os = "linux"

    [[Xorg_xcb_util_renderutil.download]]
    sha256 = "627f23dfbb4b93ee62707f12885eabce34dd9a8ef5d16d9adece81f3d4d5662a"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_renderutil_jll.jl/releases/download/Xorg_xcb_util_renderutil-v0.3.10+0/Xorg_xcb_util_renderutil.v0.3.10.powerpc64le-linux-gnu.tar.gz"
[[Xorg_xcb_util_renderutil]]
arch = "riscv64"
git-tree-sha1 = "a14d0b755df5cf09451cfdccf6148901fc63dbbc"
libc = "glibc"
os = "linux"

    [[Xorg_xcb_util_renderutil.download]]
    sha256 = "c92a974c84794f1c6e66a139a04c21dd8436f700e11e0a952ae532beffaa8ef5"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_renderutil_jll.jl/releases/download/Xorg_xcb_util_renderutil-v0.3.10+0/Xorg_xcb_util_renderutil.v0.3.10.riscv64-linux-gnu.tar.gz"
[[Xorg_xcb_util_renderutil]]
arch = "x86_64"
git-tree-sha1 = "37cb7108fbb589ecbd0b1a556668cb61a929388b"
libc = "glibc"
os = "linux"

    [[Xorg_xcb_util_renderutil.download]]
    sha256 = "7019f0fb21aa9ec98f9991a04e7f9c50ea5049614a5552986f9d97e068bd6ad5"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_renderutil_jll.jl/releases/download/Xorg_xcb_util_renderutil-v0.3.10+0/Xorg_xcb_util_renderutil.v0.3.10.x86_64-linux-gnu.tar.gz"
[[Xorg_xcb_util_renderutil]]
arch = "x86_64"
git-tree-sha1 = "0e8cc41e4d6b55e6b779b1a133352acf4a5505ea"
libc = "musl"
os = "linux"

    [[Xorg_xcb_util_renderutil.download]]
    sha256 = "e24fd2bba9c7c0b81d1b7476976d5f2658b3f5c65fb7d8541983f09eec7f0ff2"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_renderutil_jll.jl/releases/download/Xorg_xcb_util_renderutil-v0.3.10+0/Xorg_xcb_util_renderutil.v0.3.10.x86_64-linux-musl.tar.gz"
[[Xorg_xcb_util_renderutil]]
arch = "x86_64"
git-tree-sha1 = "592dec937b52060601d245fd340d7a80928a239a"
os = "freebsd"

    [[Xorg_xcb_util_renderutil.download]]
    sha256 = "2a497c7f6443fd72731e2e4c39f2f14f6e583a2b8715474898bb97151b64f1d1"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_renderutil_jll.jl/releases/download/Xorg_xcb_util_renderutil-v0.3.10+0/Xorg_xcb_util_renderutil.v0.3.10.x86_64-unknown-freebsd.tar.gz"
