[[Xorg_xcb_util_renderutil]]
arch = "armv7l"
git-tree-sha1 = "6b67ba1eba3558b814c0832c7b04371dc1c288a6"
libc = "glibc"
os = "linux"

    [[Xorg_xcb_util_renderutil.download]]
    sha256 = "d7061f276c4b87a7e60c49ef8dc4b034cb7e189cb607afcd5e9bb77a55f640d1"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_renderutil_jll.jl/releases/download/Xorg_xcb_util_renderutil-v0.3.9+0/Xorg_xcb_util_renderutil.v0.3.9.arm-linux-gnueabihf.tar.gz"
[[Xorg_xcb_util_renderutil]]
arch = "x86_64"
git-tree-sha1 = "502cdebf418a58d590bce86bc60c2c8c0bf5cdd7"
libc = "glibc"
os = "linux"

    [[Xorg_xcb_util_renderutil.download]]
    sha256 = "7c8567b62409758719328c873a1d3305fb081e3d38ee8c8c51247514b420c262"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_renderutil_jll.jl/releases/download/Xorg_xcb_util_renderutil-v0.3.9+0/Xorg_xcb_util_renderutil.v0.3.9.x86_64-linux-gnu.tar.gz"
[[Xorg_xcb_util_renderutil]]
arch = "aarch64"
git-tree-sha1 = "b62ffe0ec43458722b606e1b55bc4145b4c0f93f"
libc = "glibc"
os = "linux"

    [[Xorg_xcb_util_renderutil.download]]
    sha256 = "e1996192bec510b37c644848c49de44d2c280d9172e375cc102cc342e6dad3ae"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_renderutil_jll.jl/releases/download/Xorg_xcb_util_renderutil-v0.3.9+0/Xorg_xcb_util_renderutil.v0.3.9.aarch64-linux-gnu.tar.gz"
[[Xorg_xcb_util_renderutil]]
arch = "i686"
git-tree-sha1 = "acfb8d5b26bd5ae9a2323da021dea7d1f73d6946"
libc = "musl"
os = "linux"

    [[Xorg_xcb_util_renderutil.download]]
    sha256 = "e5ae91f9b00dffbd013dcc71c86a3631834138ea499c512bd8eae26068eff3cf"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_renderutil_jll.jl/releases/download/Xorg_xcb_util_renderutil-v0.3.9+0/Xorg_xcb_util_renderutil.v0.3.9.i686-linux-musl.tar.gz"
[[Xorg_xcb_util_renderutil]]
arch = "aarch64"
git-tree-sha1 = "c14f4ffb46d26bae8382a5f39d4cfdab9a98987f"
libc = "musl"
os = "linux"

    [[Xorg_xcb_util_renderutil.download]]
    sha256 = "32cd1637c0bdd04d7473a877f9fadfc698af3e291606ae9bf021258c05fbf83e"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_renderutil_jll.jl/releases/download/Xorg_xcb_util_renderutil-v0.3.9+0/Xorg_xcb_util_renderutil.v0.3.9.aarch64-linux-musl.tar.gz"
[[Xorg_xcb_util_renderutil]]
arch = "x86_64"
git-tree-sha1 = "b985b273a72ab2726450d54990828b7f797ceac8"
os = "freebsd"

    [[Xorg_xcb_util_renderutil.download]]
    sha256 = "e81627f1bb6711d15867af3812f204d366c700c114189e8fb324487f2dabd32e"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_renderutil_jll.jl/releases/download/Xorg_xcb_util_renderutil-v0.3.9+0/Xorg_xcb_util_renderutil.v0.3.9.x86_64-unknown-freebsd11.1.tar.gz"
[[Xorg_xcb_util_renderutil]]
arch = "powerpc64le"
git-tree-sha1 = "362e2253f81f69b051d8789c5e08cf0bc0ecd391"
libc = "glibc"
os = "linux"

    [[Xorg_xcb_util_renderutil.download]]
    sha256 = "d5f03a4bd02d9521f024cb26d18ec2b362f0d069cb81e30d73f7b573e22c8d5b"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_renderutil_jll.jl/releases/download/Xorg_xcb_util_renderutil-v0.3.9+0/Xorg_xcb_util_renderutil.v0.3.9.powerpc64le-linux-gnu.tar.gz"
[[Xorg_xcb_util_renderutil]]
arch = "i686"
git-tree-sha1 = "aa493a772b828e841a91cd63449b4731522e36df"
libc = "glibc"
os = "linux"

    [[Xorg_xcb_util_renderutil.download]]
    sha256 = "f6b06395af04d9778af814489242bb5fad68cb0c4c3b0b4c1e079080478e14cc"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_renderutil_jll.jl/releases/download/Xorg_xcb_util_renderutil-v0.3.9+0/Xorg_xcb_util_renderutil.v0.3.9.i686-linux-gnu.tar.gz"
[[Xorg_xcb_util_renderutil]]
arch = "x86_64"
git-tree-sha1 = "f85458ae0b7986bc2696ec38535cd761ca7feca9"
libc = "musl"
os = "linux"

    [[Xorg_xcb_util_renderutil.download]]
    sha256 = "a8341af6536de6168a0268e0ef77cd88aa84aa8c0c001b7f25313515647fdb0b"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_renderutil_jll.jl/releases/download/Xorg_xcb_util_renderutil-v0.3.9+0/Xorg_xcb_util_renderutil.v0.3.9.x86_64-linux-musl.tar.gz"
[[Xorg_xcb_util_renderutil]]
arch = "armv7l"
git-tree-sha1 = "8475b5ea3d89a2585f8a9184f51f3875a9e10f70"
libc = "musl"
os = "linux"

    [[Xorg_xcb_util_renderutil.download]]
    sha256 = "b2b0845b0737c932cc6ed4dbd8e82a85d2b675b2425b376e8ee12d94d3d8a195"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_renderutil_jll.jl/releases/download/Xorg_xcb_util_renderutil-v0.3.9+0/Xorg_xcb_util_renderutil.v0.3.9.arm-linux-musleabihf.tar.gz"
